### ISSUE TITLE
Roadmap for Preview Version

### ISSUE THREAD

**Issue by dtretyakov** [rugpanov/TeamCity-extension-for-VSCode#1]
Following tasks should be done for Preview Version of TeamCity extension for VS Code:

- [] Get list of modified files from Git SCM Provider
- [] Get list of modified files from TFVC SCM Provider
- [] Get repository info from Git SCM Provider
- [] Get repository info from TFVC SCM Provider

**Comment by ekoshkin** [comment]
Please consider using TeamCity REST API to access server instead of outdated XML-RPC.
Feel free to contact me to get details.
